In [74]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
#from utility import review_to_words
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


#def data_load(file = 'train_E6oV3lV.csv', test_split: float = 0.1, random_seed: int = 3):
df = pd.read_csv('train_E6oV3lV.csv')
df = df.drop(['id'], axis=1)
#X = df['tweet']
#y = df['label']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
#train_X, train_y = shuffle(X_train, y_train)
#test_X, test_y = shuffle(X_test, y_test)
#train_X = train_X.apply(lambda x:review_to_words(x))

In [75]:
df.head(4)

label                                              tweet
0      0   @user when a father is dysfunctional and is s...
1      0  @user @user thanks for #lyft credit i can't us...
2      0                                bihday your majesty
3      0  #model   i love u take with u all the time in ...

In [76]:
df.shape

(31962, 2)

In [77]:
#print the train and test tweet
#print(train_X[1])
#print(train_y[1])

In [78]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import *

import re
from bs4 import BeautifulSoup

def review_to_words(review):
    nltk.download("stopwords", quiet=True)
    stemmer = PorterStemmer()
    
    text = BeautifulSoup(review, "html.parser").get_text() # Remove HTML tags
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower()) # Convert to lower case
    words = text.split() # Split string into words
    words = [w for w in words if w not in stopwords.words("english")] # Remove stopwords
    words = [PorterStemmer().stem(w) for w in words] # stem
    
    return words

In [79]:
#try apply for one of the tweets
df['new'] = df['tweet'].apply(review_to_words)
print(df)

C:\Users\Dell\AppData\Local\Temp\ipykernel_2064\2137687332.py:12: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(review, "html.parser").get_text() # Remove HTML tags


       label                                              tweet  \
0          0   @user when a father is dysfunctional and is s...   
1          0  @user @user thanks for #lyft credit i can't us...   
2          0                                bihday your majesty   
3          0  #model   i love u take with u all the time in ...   
4          0             factsguide: society now    #motivation   
...      ...                                                ...   
31957      0  ate @user isz that youuu?😍😍😍😍😍ð...   
31958      0    to see nina turner on the airwaves trying to...   
31959      0  listening to sad songs on a monday morning otw...   
31960      1  @user #sikh #temple vandalised in in #calgary,...   
31961      0                   thank you @user for you follow     

                                                     new  
0      [user, father, dysfunct, selfish, drag, kid, d...  
1      [user, user, thank, lyft, credit, use, caus, o...  
2                 

In [80]:
df['new']

0        [user, father, dysfunct, selfish, drag, kid, d...
1        [user, user, thank, lyft, credit, use, caus, o...
2                                        [bihday, majesti]
3                      [model, love, u, take, u, time, ur]
4                              [factsguid, societi, motiv]
                               ...                        
31957                              [ate, user, isz, youuu]
31958    [see, nina, turner, airwav, tri, wrap, mantl, ...
31959    [listen, sad, song, monday, morn, otw, work, sad]
31960    [user, sikh, templ, vandalis, calgari, wso, co...
31961                                [thank, user, follow]
Name: new, Length: 31962, dtype: object

In [53]:
X=df['new'].values
Y= df['label'].values

In [82]:
Y

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [93]:
X_train,X_test,Y_train,Y_test=train_test_split(X, Y,stratify=Y, test_size=0.2)

In [94]:
X_train

14695    just enjoying the day. #freespirit #hippie #hi...
18188      is defunding aboion and sending you to the #...
13579       coffe go to work 😄😄   #miercolesbonitos 
2066     salute to all fathers active in they kids live...
2802     confirmation teacher? the youth director is in...
                               ...                        
20341    wow. i really ate the last of the fried chicke...
11593    what makes your little one   today? ad  #mom #...
20594    #beachday   gorilla simulator: you need to do ...
21973    set of 4 moroc... gbp 19.00 get here:  #shop #...
21097    dang i clicked on this girls selfies cause she...
Name: tweet, Length: 25569, dtype: object

In [95]:
X_test

11853     @user have had setup #bbc #iplayer to watch n...
24517    all tickets have been delivered, lets get read...
8732     @user # in other words creditors do not want  ...
12285     @user .@user kill an #animal &amp; market it ...
3057             and destructive socialists #maddow @user 
                               ...                        
24964    #interested in what i do? lets #chat and have ...
7256       @user saturday shooting @user   #beretta @user 
14156    every monday, i tell myself that i will give t...
3236     my "happy things place" ☺️ all my scuba st...
13962    shout out to @user 4 following me! can't wait ...
Name: tweet, Length: 6393, dtype: object

In [96]:
Y_train

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [97]:
Y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [98]:
#cache_data = dict(words_train=train_X, words_test=test_X,
                              #labels_train=train_y, labels_test=test_y)
#with open('preprocessed.pkl', "wb") as f:
    #pickle.dump(cache_data, f)

#print("Wrote preprocessed data to cache file")

In [99]:
#def convert_and_pad(word_dict, sentence, pad=256):
    #NOWORD = 0 # We will use 0 to represent the 'no word' category
    #INFREQ = 1 # and we use 1 to represent the infrequent words, i.e., words not appearing in word_dict
    
    #working_sentence = [NOWORD] * pad
    
    #for word_index, word in enumerate(sentence[:pad]):
        #if word in word_dict:
            working_sentence[word_index] = word_dict[word]
        #else:
            #working_sentence[word_index] = INFREQ
            
    #return working_sentence, min(len(sentence), pad)

#def convert_and_pad_data(word_dict, data, pad=256):
    #result = []
    #lengths = []
    
    #for sentence in data:
        #converted, leng = convert_and_pad(word_dict, sentence, pad)
        #result.append(converted)
        #lengths.append(leng)
        
    #return np.array(result), np.array(lengths)

IndentationError: unexpected indent (864916974.py, line 9)

In [100]:
#train_X, train_X_len = convert_and_pad_data(word_dict, train_X)
#test_X, test_X_len = convert_and_pad_data(word_dict, test_X)

In [101]:
# Remove invalid entries
train_X = [doc for doc in X_train if isinstance(doc, (list, str))]
test_X = [doc for doc in X_test if isinstance(doc, (list, str))]

In [102]:
train_X_new = [" ".join(doc) if isinstance(doc, list) else doc for doc in train_X]
test_X_new = [" ".join(doc) if isinstance(doc, list) else doc for doc in test_X]

In [62]:
# Convert lists of words back into strings
#train_X = [" ".join(doc) for doc in X_train]
#test_X = [" ".join(doc) for doc in X_test]

In [103]:
print("Number of training samples:", len(train_X_new))
print("Number of testing samples:", len(test_X_new))

Number of training samples: 25569
Number of testing samples: 6393


In [ ]:
#Feature extraction or converting the features into numerical values

In [104]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [105]:
tfidf_vectorizer = TfidfVectorizer()
    

In [106]:
# Step 2: Fit the vectorizer on training data and transform train_X
train_X_tfidf = tfidf_vectorizer.fit_transform(train_X_new)

# Step 3: Transform test_X using the same vectorizer
test_X_tfidf = tfidf_vectorizer.transform(test_X_new)

In [107]:
train_X_tfidf.shape

(25569, 36035)

In [108]:
train_X_tfidf

<25569x36035 sparse matrix of type '<class 'numpy.float64'>'
	with 293491 stored elements in Compressed Sparse Row format>